CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(40) NOT NULL,
    email varchar(40) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(200),
    requestor_id bigint,
    CONSTRAINT PK_REQUESTS PRIMARY KEY (id),
    CONSTRAINT FK_REQUESTS_USERS FOREIGN KEY (requestor_id) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(40) NOT NULL,
    description varchar(120) NOT NULL,
    is_available boolean,
    owner_id bigint,
    request_id bigint,
    CONSTRAINT PK_ITEMS PRIMARY KEY (id),
    CONSTRAINT FK_ITEMS_USERS FOREIGN KEY (owner_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT FK_ITEMS_REQUESTS FOREIGN KEY (request_id) REFERENCES requests ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id bigint,
    booker_id bigint,
    status varchar(10),
    CONSTRAINT PK_BOOKINGS PRIMARY KEY (id),
    CONSTRAINT FK_BOOKINGS_USERS FOREIGN KEY (booker_id) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(200),
    item_id bigint,
    author_id bigint,
    created timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COMMENTS PRIMARY KEY (id),
    CONSTRAINT FK_COMMENTS_ITEMS FOREIGN KEY (item_id) REFERENCES items ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_USERS FOREIGN KEY (author_id) REFERENCES users ON DELETE CASCADE
);

